### ISSUE TITLE
Images saved to node from ComfyShop have reduced quality

### ISSUE THREAD

**Issue by rabidcopy** [ManglerFTW/ComfyI2I#9] opened 2023-09-28 21:45 UTC
Edit: Issue was originally made for a different issue but it was solved. See https://github.com/ManglerFTW/ComfyI2I/issues/9#issuecomment-1740089763.
I'm not sure if I'm doing something wrong but I can't seem to get the Inpaint Segments node to work as shown in the examples. From my understanding it's supposed to crop every part of the mask and send that as individual pieces of the original image with accompanying masks, but when I do that it only puts out a warped mask and one image to be VAE encoded.
![image](https://github.com/ManglerFTW/ComfyI2I/assets/8052832/103c4646-754f-4ae7-b2ee-9a0a2c053592)

**Comment by rabidcopy** [comment] 2023-09-28 21:52
I set separate_mask to 1 and now it seems to work? When I tried before it gave an error. But then I tried again and no error?
```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/home/rabid/Documents/ComfyOmega/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rabid/Documents/ComfyOmega/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rabid/Documents/ComfyOmega/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rabid/Documents/ComfyOmega/comfy_extras/nodes_mask.py", line 125, in image_to_mask
    mask = image[0, :, :, channels.index(channel)]
           ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: too many indices for tensor of dimension 3
```
![image](https://github.com/ManglerFTW/ComfyI2I/assets/8052832/0c66d283-68c4-4d3c-b495-94668aed5052)

**Comment by rabidcopy** [comment] 2023-09-28 22:39
I think this is resolved but there's one other thing I wanted to inquire about. When using the ComfyShop editor, it seems images saved to the node incur a resolution/quality reduction.
Original Image:
![image](https://github.com/ManglerFTW/ComfyI2I/assets/8052832/4552dacd-0b2a-4b36-82fa-e8fab8e52f57)
Image saved to node from ComfyShop:
![image](https://github.com/ManglerFTW/ComfyI2I/assets/8052832/b74b14c7-0fe7-4cfb-8aa8-e7dacb0fc2f4)
Close-up comparison of image before and after editing it in ComfyShop:
![image](https://github.com/ManglerFTW/ComfyI2I/assets/8052832/6db09c00-2dfe-475c-973b-b27cb14398c8)

**Comment by ManglerFTW** [comment] 2023-09-29 00:42
Hey! For the first issue you had it right setting separate_mask to 1. Not sure about the errors cause they don't look like they are coming from ComfyI2I.py

As for the other part. I am working on finding out where the issue is coming from. I'll keep you posted.

**Comment by ManglerFTW** [comment] 2023-09-29 03:20
OK I've made some tweaks to the resizeHandler to make sure the image size doesn't change along with the Canvas size. Can you give it another try and see if you are still experiencing any issues?

**Comment by rabidcopy** [comment] 2023-09-29 03:31
> OK I've made some tweaks to the resizeHandler to make sure the image size doesn't change along with the Canvas size. Can you give it another try and see if you are still experiencing any issues?

Git pull'd and strangely the issue persists. If it matters I'm using Firefox.
![image](https://github.com/ManglerFTW/ComfyI2I/assets/8052832/af5d6342-9b6f-405e-8c18-7eb5009b754f)
![image](https://github.com/ManglerFTW/ComfyI2I/assets/8052832/5569926f-1ce9-482c-aa99-e17eaa4d2968)

**Comment by rabidcopy** [comment] 2023-09-29 03:38
I think it has something to do with https://github.com/ManglerFTW/ComfyI2I/blob/7adf0fa90e9c16e71fa26b837496d77ac58073e5/js/ComfyShop.js#L597
Changing it to 1.0 seems to get rid of the resolution reduction, but the resulting saved image does look like it underwent resampling and isn't as sharp still.
![image](https://github.com/ManglerFTW/ComfyI2I/assets/8052832/48b4ee5e-60fa-4c73-968a-573adb12875b)
![image](https://github.com/ManglerFTW/ComfyI2I/assets/8052832/a891666d-f02c-4bf6-a78a-6850f12ee61b)
![image](https://github.com/ManglerFTW/ComfyI2I/assets/8052832/5463b972-ecc6-4446-9e2b-1d92726d1e0f)
![image](https://github.com/ManglerFTW/ComfyI2I/assets/8052832/c92a8152-6bf0-4566-96d2-17fc54df61b6)

**Comment by ManglerFTW** [comment] 2023-09-29 03:43
Hmm. I should have more time for a deeper dive into it tomorrow afternoon. I'll post an update as soon as I can get it figured out.

**Comment by ManglerFTW** [comment] 2023-09-30 07:45
Just pushed a fix. It should be lossless now. It was tested as a difference layer in photoshop and seems to be working for me. Please let me know if you get better results. I've also added an option to work in full resolution by pressing f or fit to screen with shift+f. Should make things a little better for larger image resolutions.


![Capture](https://github.com/ManglerFTW/ComfyI2I/assets/113069374/e11be3e1-f2bc-4186-bff3-808c3c359f99)

**Closed** 2023-10-04 16:23 UTC
